#! /usr/bin/env python3

"""Validate mwb_dat against the delivered CORDC netCDF.

Every dwell in mwb458d02_gps_timeseries.nc is matched to its source .dat by
first-record timestamp, then compared sample by sample.  Run with:

    python3 test_mwb_dat.py [raw_data/458] [mwb458d02_gps_timeseries.nc]

Requires netCDF4 only for this test; mwb_dat itself needs numpy alone.
"""

import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "src"))

import mwb_dat

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DEFAULT_RAW = os.path.join(REPO, "data", "raw_dat", "458")
# Must be a CORDC-delivered file, not one regenerated by mwb_nc: the sog/cog/
# pdop checks below reproduce the delivered files' lossy encoding, which
# mwb_nc deliberately does not use.  netcdf.other holds the originals.
# The CORDC-delivered files are NOT redistributed in this repository (see
# LICENSE-DATA). This test validates the parser against them, so without a
# local copy it skips rather than fails. CORDC users: pass your own path.
DEFAULT_NC = os.path.join(REPO, "data", "cordc_delivered",
                          "mwb458d02_gps_timeseries.nc")

# Fields the netCDF stores at full float32/int precision: these must agree
# bit-for-bit.  (nc name, decoded name)
EXACT = [("time", "time"), ("lat", "lat"), ("lon", "lon"),
         ("u", "u"), ("v", "v"), ("w", "w"), ("numsats", "numsats")]


def main(raw_root=DEFAULT_RAW, nc_path=DEFAULT_NC):
    if not os.path.exists(nc_path):
        print(f"SKIP -- no CORDC-delivered file at {nc_path}\n"
              "  This test checks that mwb_dat reproduces the delivered CORDC\n"
              "  NetCDF bit-for-bit. Those files are not redistributed here\n"
              "  (see LICENSE-DATA). With your own copy:\n"
              f"    python3 {os.path.basename(__file__)} "
              "<raw_dat_dir> <delivered.nc>")
        return 0

    import netCDF4

    nc = netCDF4.Dataset(nc_path)
    for v in nc.variables.values():
        v.set_auto_mask(False)
        v.set_auto_scale(False)          # compare against the stored integers
    nc_time = nc.variables["time"][:].astype(np.int64)
    ndwell, nsamp = nc_time.shape

    ts, files = mwb_dat.read_tree(raw_root, return_files=True)
    assert len(ts) == mwb_dat.SAMPLES_PER_DWELL * len(files), \
        f"{len(ts)} records from {len(files)} files -- unexpected duplicates or gaps"

    # index each source dwell by its first timestamp
    by_start = {}
    for k in range(len(files)):
        block = ts[ts["dwell"] == k]
        by_start[int(block["time"][0])] = block
    assert len(by_start) == len(files), "two dwells share a start time"

    failures, worst = [], {}
    matched = []
    for i in range(ndwell):
        start = int(nc_time[i, 0])
        if start not in by_start:
            failures.append(f"dwell {i}: no .dat starts at {np.datetime64(start, 'ms')}")
            continue
        d = by_start[start]
        matched.append(start)
        assert len(d) == nsamp, f"dwell {i}: {len(d)} records vs {nsamp}"

        for ncname, myname in EXACT:
            a = np.asarray(d[myname], dtype=np.float64)
            b = np.asarray(nc.variables[ncname][i], dtype=np.float64)
            err = np.abs(a - b).max()
            worst[ncname] = max(worst.get(ncname, 0.0), err)
            if err != 0.0:
                failures.append(f"dwell {i} {ncname}: max|diff| = {err!r} (expected 0)")

        # quantized-on-write fields: reproduce the netCDF's own encoding
        checks = [
            ("sog", np.floor(np.asarray(d["sog"], np.float64) * 10 + 0.5), 0),
            ("cog", np.floor(np.asarray(d["cog"], np.float64) * 10 + 0.5), 1),
            ("pdop", np.round(np.asarray(d["pdop"], np.float64)), 0),
        ]
        for ncname, mine, tol_counts in checks:
            b = np.asarray(nc.variables[ncname][i], dtype=np.float64)
            bad = int((np.abs(mine - b) > tol_counts).sum())
            worst[ncname] = max(worst.get(ncname, 0), bad)
            if bad:
                failures.append(f"dwell {i} {ncname}: {bad}/{nsamp} samples "
                                f"off by more than {tol_counts} count(s)")

    print(f"raw .dat bursts read      : {len(files)}")
    print(f"netCDF dwells             : {ndwell}")
    print(f"matched to a .dat         : {len(matched)}")
    print(f"bursts absent from netCDF : {len(files) - len(matched)}")
    print(f"records, raw vs netCDF    : {len(ts)} vs {ndwell * nsamp} "
          f"(+{100 * len(ts) / (ndwell * nsamp) - 100:.1f}%)")
    print()
    print("max |raw - netCDF| per field (0 = bit-exact):")
    for ncname, _ in EXACT:
        print(f"  {ncname:9s} {worst.get(ncname, float('nan')):.6g}")
    print("quantized fields, samples exceeding tolerance:")
    for ncname in ("sog", "cog", "pdop"):
        print(f"  {ncname:9s} {worst.get(ncname, 0)}")
    print()

    if failures:
        print(f"FAIL -- {len(failures)} problem(s):")
        for f in failures[:20]:
            print("  " + f)
        if len(failures) > 20:
            print(f"  ... and {len(failures) - 20} more")
        return 1
    print("PASS -- every netCDF dwell reproduced from the raw .dat files.")
    return 0


if __name__ == "__main__":
    raw = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_RAW
    ncp = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_NC
    sys.exit(main(raw, ncp))
